unique_name: dataset_Settings
object_type: dataset
label: Settings
columns:
  - name: Business Unit
    data_type: string
  - name: Hide Data
    data_type: string
  - name: countrows1
    data_type: int
    sql: '1'
connection_id: connection_POC
table: Settings
