unique_name: Forecasted BMcD Labor Burden Costs_POC Values
object_type: metric_calc
label: Forecasted BMcD Labor Burden Costs
expression: >-
  0 /*DIVIDE(CALCULATE(Sum('POC Values'[.Forecast Cost]),'POC Values'[Labor
  Detail]="Burden"),[HasOneCurrency]) TODO: Update with valid MDX expression*/
format: '#,0.00'
