unique_name: Product Strategy Id
object_type: metric
label: Product Strategy Id
calculation_method: count non-null
column: Product Strategy Id
dataset: dataset_Leaf_Product_Family
format: '0'
unrelated_dimensions_handling: repeat
