unique_name: ProductFamilyID_SalesPlan
object_type: metric
label: ProductFamilyID count on SalesPlan
calculation_method: count non-null
column: ProductFamilyID
dataset: dataset_SalesPlan
format: '0'
unrelated_dimensions_handling: repeat
