unique_name: Product Strategy Id Current
object_type: metric
label: Product Strategy Id Current
calculation_method: sum
column: Product Strategy Id Current
dataset: dataset_Leaf_Product_Family
format: '0'
unrelated_dimensions_handling: repeat
