unique_name: ProductFamilyId
object_type: metric
label: ProductFamilyId
calculation_method: count non-null
column: ProductFamilyId
dataset: dataset_Sales_Credit
format: '0'
unrelated_dimensions_handling: repeat
