unique_name: ProductFamilyId_Pipeline Outcome
object_type: metric
label: ProductFamilyId count on Pipeline Outcome
calculation_method: count non-null
column: ProductFamilyId
dataset: dataset_Pipeline_Outcome
format: '0'
unrelated_dimensions_handling: repeat
