unique_name: ProductKey_Starting ASV
object_type: metric
label: ProductKey count on Starting ASV
calculation_method: count non-null
column: ProductKey
dataset: dataset_Starting_ASV
format: '0'
unrelated_dimensions_handling: repeat
